// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: overgivechain/donation/v1/donation.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Donation struct {
	Id                 uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignId         string `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Amount             string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency           string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentReferenceId string `protobuf:"bytes,5,opt,name=payment_reference_id,json=paymentReferenceId,proto3" json:"payment_reference_id,omitempty"`
	DonationHash       string `protobuf:"bytes,6,opt,name=donation_hash,json=donationHash,proto3" json:"donation_hash,omitempty"`
	MetadataHash       string `protobuf:"bytes,7,opt,name=metadata_hash,json=metadataHash,proto3" json:"metadata_hash,omitempty"`
	Creator            string `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	RecordedAt         int64  `protobuf:"varint,9,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
}

func (m *Donation) Reset()         { *m = Donation{} }
func (m *Donation) String() string { return proto.CompactTextString(m) }
func (*Donation) ProtoMessage()    {}
func (*Donation) Descriptor() ([]byte, []int) {
	return fileDescriptor_452ba7f4b7091131, []int{0}
}
func (m *Donation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Donation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Donation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Donation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Donation.Merge(m, src)
}
func (m *Donation) XXX_Size() int {
	return m.Size()
}
func (m *Donation) XXX_DiscardUnknown() {
	xxx_messageInfo_Donation.DiscardUnknown(m)
}

var xxx_messageInfo_Donation proto.InternalMessageInfo

func (m *Donation) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Donation) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *Donation) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Donation) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Donation) GetPaymentReferenceId() string {
	if m != nil {
		return m.PaymentReferenceId
	}
	return ""
}

func (m *Donation) GetDonationHash() string {
	if m != nil {
		return m.DonationHash
	}
	return ""
}

func (m *Donation) GetMetadataHash() string {
	if m != nil {
		return m.MetadataHash
	}
	return ""
}

func (m *Donation) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Donation) GetRecordedAt() int64 {
	if m != nil {
		return m.RecordedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Donation)(nil), "overgivechain.donation.v1.Donation")
}

func init() {
	proto.RegisterFile("overgivechain/donation/v1/donation.proto", fileDescriptor_452ba7f4b7091131)
}

var fileDescriptor_452ba7f4b7091131 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xbf, 0x4e, 0xfb, 0x30,
	0x10, 0xc7, 0xeb, 0xb4, 0xbf, 0xfe, 0xf1, 0x0f, 0x18, 0xac, 0x0a, 0x99, 0x0e, 0x69, 0x05, 0x4b,
	0x16, 0x5a, 0x2a, 0x26, 0x46, 0x10, 0x03, 0x5d, 0x33, 0xb2, 0x44, 0x47, 0x7c, 0x24, 0x1e, 0x62,
	0x47, 0xae, 0x1b, 0xd1, 0xb7, 0xe0, 0x29, 0x78, 0x16, 0xc6, 0x8e, 0x8c, 0xa8, 0x7d, 0x11, 0x14,
	0xa7, 0x0e, 0x62, 0xbb, 0xfb, 0x7e, 0x3e, 0xb6, 0x74, 0x77, 0x34, 0xd2, 0x15, 0x9a, 0x4c, 0x56,
	0x98, 0xe6, 0x20, 0xd5, 0x42, 0x68, 0x05, 0x56, 0x6a, 0xb5, 0xa8, 0x96, 0x6d, 0x3d, 0x2f, 0x8d,
	0xb6, 0x9a, 0x5d, 0xfc, 0x31, 0xe7, 0x2d, 0xad, 0x96, 0x93, 0x71, 0xa6, 0x33, 0xed, 0xac, 0x45,
	0x5d, 0x35, 0x0f, 0x2e, 0x3f, 0x02, 0x3a, 0x7c, 0x3c, 0x5a, 0xec, 0x8c, 0x06, 0x52, 0x70, 0x32,
	0x23, 0x51, 0x2f, 0x0e, 0xa4, 0x60, 0x53, 0xfa, 0x3f, 0x85, 0xa2, 0x04, 0x99, 0xa9, 0x44, 0x0a,
	0x1e, 0xcc, 0x48, 0x34, 0x8a, 0xa9, 0x8f, 0x56, 0x82, 0x9d, 0xd3, 0x3e, 0x14, 0x7a, 0xa3, 0x2c,
	0xef, 0x3a, 0x76, 0xec, 0xd8, 0x84, 0x0e, 0xd3, 0x8d, 0x31, 0xa8, 0xd2, 0x2d, 0xef, 0x39, 0xd2,
	0xf6, 0xec, 0x86, 0x8e, 0x4b, 0xd8, 0x16, 0xa8, 0x6c, 0x62, 0xf0, 0x15, 0xeb, 0x10, 0xeb, 0xdf,
	0xff, 0x39, 0x8f, 0x1d, 0x59, 0xec, 0xd1, 0x4a, 0xb0, 0x2b, 0x7a, 0xea, 0x07, 0x49, 0x72, 0x58,
	0xe7, 0xbc, 0xef, 0xd4, 0x13, 0x1f, 0x3e, 0xc1, 0x3a, 0xaf, 0xa5, 0x02, 0x2d, 0x08, 0xb0, 0xd0,
	0x48, 0x83, 0x46, 0xf2, 0xa1, 0x93, 0x38, 0x1d, 0xa4, 0x06, 0xc1, 0x6a, 0xc3, 0x87, 0x0e, 0xfb,
	0xb6, 0x1e, 0xd5, 0x60, 0xaa, 0x8d, 0x40, 0x91, 0x80, 0xe5, 0xa3, 0x19, 0x89, 0xba, 0x31, 0xf5,
	0xd1, 0xbd, 0x7d, 0xb8, 0xfb, 0xdc, 0x87, 0x64, 0xb7, 0x0f, 0xc9, 0xf7, 0x3e, 0x24, 0xef, 0x87,
	0xb0, 0xb3, 0x3b, 0x84, 0x9d, 0xaf, 0x43, 0xd8, 0x79, 0x9e, 0xfa, 0x9d, 0x5f, 0x37, 0xe7, 0x79,
	0xfb, 0x3d, 0x90, 0xdd, 0x96, 0xb8, 0x7e, 0xe9, 0xbb, 0x55, 0xdf, 0xfe, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x89, 0x01, 0x90, 0xc1, 0xc7, 0x01, 0x00, 0x00,
}

func (m *Donation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Donation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Donation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RecordedAt != 0 {
		i = encodeVarintDonation(dAtA, i, uint64(m.RecordedAt))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintDonation(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.MetadataHash) > 0 {
		i -= len(m.MetadataHash)
		copy(dAtA[i:], m.MetadataHash)
		i = encodeVarintDonation(dAtA, i, uint64(len(m.MetadataHash)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.DonationHash) > 0 {
		i -= len(m.DonationHash)
		copy(dAtA[i:], m.DonationHash)
		i = encodeVarintDonation(dAtA, i, uint64(len(m.DonationHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.PaymentReferenceId) > 0 {
		i -= len(m.PaymentReferenceId)
		copy(dAtA[i:], m.PaymentReferenceId)
		i = encodeVarintDonation(dAtA, i, uint64(len(m.PaymentReferenceId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Currency) > 0 {
		i -= len(m.Currency)
		copy(dAtA[i:], m.Currency)
		i = encodeVarintDonation(dAtA, i, uint64(len(m.Currency)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintDonation(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CampaignId) > 0 {
		i -= len(m.CampaignId)
		copy(dAtA[i:], m.CampaignId)
		i = encodeVarintDonation(dAtA, i, uint64(len(m.CampaignId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintDonation(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDonation(dAtA []byte, offset int, v uint64) int {
	offset -= sovDonation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Donation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovDonation(uint64(m.Id))
	}
	l = len(m.CampaignId)
	if l > 0 {
		n += 1 + l + sovDonation(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovDonation(uint64(l))
	}
	l = len(m.Currency)
	if l > 0 {
		n += 1 + l + sovDonation(uint64(l))
	}
	l = len(m.PaymentReferenceId)
	if l > 0 {
		n += 1 + l + sovDonation(uint64(l))
	}
	l = len(m.DonationHash)
	if l > 0 {
		n += 1 + l + sovDonation(uint64(l))
	}
	l = len(m.MetadataHash)
	if l > 0 {
		n += 1 + l + sovDonation(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovDonation(uint64(l))
	}
	if m.RecordedAt != 0 {
		n += 1 + sovDonation(uint64(m.RecordedAt))
	}
	return n
}

func sovDonation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDonation(x uint64) (n int) {
	return sovDonation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Donation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDonation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Donation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Donation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDonation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDonation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDonation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDonation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CampaignId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDonation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDonation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDonation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Currency", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDonation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDonation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDonation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Currency = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentReferenceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDonation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDonation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDonation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentReferenceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DonationHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDonation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDonation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDonation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DonationHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDonation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDonation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDonation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDonation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDonation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDonation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordedAt", wireType)
			}
			m.RecordedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDonation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDonation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDonation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDonation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDonation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDonation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDonation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDonation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDonation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDonation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDonation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDonation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDonation = fmt.Errorf("proto: unexpected end of group")
)
