// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: overgivechain/donation/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a944054dfe2c36, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a944054dfe2c36, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// Request for Get All Donations
type QueryDonationsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDonationsRequest) Reset()         { *m = QueryDonationsRequest{} }
func (m *QueryDonationsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDonationsRequest) ProtoMessage()    {}
func (*QueryDonationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a944054dfe2c36, []int{2}
}
func (m *QueryDonationsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDonationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDonationsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDonationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDonationsRequest.Merge(m, src)
}
func (m *QueryDonationsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDonationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDonationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDonationsRequest proto.InternalMessageInfo

func (m *QueryDonationsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// Reponse for Get All Donations
type QueryDonationsResponse struct {
	Donations  []*Donation         `protobuf:"bytes,1,rep,name=donations,proto3" json:"donations,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDonationsResponse) Reset()         { *m = QueryDonationsResponse{} }
func (m *QueryDonationsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDonationsResponse) ProtoMessage()    {}
func (*QueryDonationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a944054dfe2c36, []int{3}
}
func (m *QueryDonationsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDonationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDonationsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDonationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDonationsResponse.Merge(m, src)
}
func (m *QueryDonationsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDonationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDonationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDonationsResponse proto.InternalMessageInfo

func (m *QueryDonationsResponse) GetDonations() []*Donation {
	if m != nil {
		return m.Donations
	}
	return nil
}

func (m *QueryDonationsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// Request for Get Donation By ID
type QueryGetDonationRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetDonationRequest) Reset()         { *m = QueryGetDonationRequest{} }
func (m *QueryGetDonationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDonationRequest) ProtoMessage()    {}
func (*QueryGetDonationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a944054dfe2c36, []int{4}
}
func (m *QueryGetDonationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDonationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDonationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDonationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDonationRequest.Merge(m, src)
}
func (m *QueryGetDonationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDonationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDonationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDonationRequest proto.InternalMessageInfo

func (m *QueryGetDonationRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Response for Get Donation By ID
type QueryGetDonationResponse struct {
	Donation *Donation `protobuf:"bytes,1,opt,name=donation,proto3" json:"donation,omitempty"`
}

func (m *QueryGetDonationResponse) Reset()         { *m = QueryGetDonationResponse{} }
func (m *QueryGetDonationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDonationResponse) ProtoMessage()    {}
func (*QueryGetDonationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a944054dfe2c36, []int{5}
}
func (m *QueryGetDonationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDonationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDonationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDonationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDonationResponse.Merge(m, src)
}
func (m *QueryGetDonationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDonationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDonationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDonationResponse proto.InternalMessageInfo

func (m *QueryGetDonationResponse) GetDonation() *Donation {
	if m != nil {
		return m.Donation
	}
	return nil
}

// Request for Get Donation By Hash
type QueryDonationByHashRequest struct {
	DonationHash string `protobuf:"bytes,1,opt,name=donation_hash,json=donationHash,proto3" json:"donation_hash,omitempty"`
}

func (m *QueryDonationByHashRequest) Reset()         { *m = QueryDonationByHashRequest{} }
func (m *QueryDonationByHashRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDonationByHashRequest) ProtoMessage()    {}
func (*QueryDonationByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a944054dfe2c36, []int{6}
}
func (m *QueryDonationByHashRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDonationByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDonationByHashRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDonationByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDonationByHashRequest.Merge(m, src)
}
func (m *QueryDonationByHashRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDonationByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDonationByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDonationByHashRequest proto.InternalMessageInfo

func (m *QueryDonationByHashRequest) GetDonationHash() string {
	if m != nil {
		return m.DonationHash
	}
	return ""
}

// Response for Get Donation By Hash
type QueryDonationByHashResponse struct {
	Donation *Donation `protobuf:"bytes,1,opt,name=donation,proto3" json:"donation,omitempty"`
}

func (m *QueryDonationByHashResponse) Reset()         { *m = QueryDonationByHashResponse{} }
func (m *QueryDonationByHashResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDonationByHashResponse) ProtoMessage()    {}
func (*QueryDonationByHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a944054dfe2c36, []int{7}
}
func (m *QueryDonationByHashResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDonationByHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDonationByHashResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDonationByHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDonationByHashResponse.Merge(m, src)
}
func (m *QueryDonationByHashResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDonationByHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDonationByHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDonationByHashResponse proto.InternalMessageInfo

func (m *QueryDonationByHashResponse) GetDonation() *Donation {
	if m != nil {
		return m.Donation
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "overgivechain.donation.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "overgivechain.donation.v1.QueryParamsResponse")
	proto.RegisterType((*QueryDonationsRequest)(nil), "overgivechain.donation.v1.QueryDonationsRequest")
	proto.RegisterType((*QueryDonationsResponse)(nil), "overgivechain.donation.v1.QueryDonationsResponse")
	proto.RegisterType((*QueryGetDonationRequest)(nil), "overgivechain.donation.v1.QueryGetDonationRequest")
	proto.RegisterType((*QueryGetDonationResponse)(nil), "overgivechain.donation.v1.QueryGetDonationResponse")
	proto.RegisterType((*QueryDonationByHashRequest)(nil), "overgivechain.donation.v1.QueryDonationByHashRequest")
	proto.RegisterType((*QueryDonationByHashResponse)(nil), "overgivechain.donation.v1.QueryDonationByHashResponse")
}

func init() {
	proto.RegisterFile("overgivechain/donation/v1/query.proto", fileDescriptor_10a944054dfe2c36)
}

var fileDescriptor_10a944054dfe2c36 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x41, 0x6b, 0x13, 0x4f,
	0x18, 0xc6, 0x33, 0xf9, 0xff, 0x5b, 0x9a, 0xb7, 0x5a, 0x70, 0xac, 0x5a, 0x57, 0xd9, 0xda, 0x8d,
	0xc6, 0xa4, 0xda, 0x1d, 0x37, 0x45, 0xa1, 0x78, 0x90, 0x84, 0x62, 0x3d, 0xd6, 0x3d, 0x5a, 0xb0,
	0x4c, 0x9a, 0x61, 0xb3, 0x60, 0x76, 0xb6, 0x99, 0x6d, 0x30, 0x94, 0x5e, 0xfc, 0x04, 0xa2, 0x77,
	0x4f, 0x22, 0x82, 0x17, 0x3f, 0x83, 0xa7, 0x1e, 0x0b, 0x5e, 0x3c, 0x89, 0x24, 0x82, 0x5f, 0x43,
	0x76, 0x66, 0x36, 0x71, 0x1b, 0xd3, 0x24, 0xe0, 0x25, 0x2c, 0x93, 0xe7, 0x79, 0xdf, 0xdf, 0xfb,
	0xec, 0x3b, 0x0b, 0xb7, 0x78, 0x9b, 0xb5, 0x3c, 0xbf, 0xcd, 0xf6, 0x1a, 0xd4, 0x0f, 0x48, 0x9d,
	0x07, 0x34, 0xf2, 0x79, 0x40, 0xda, 0x0e, 0xd9, 0x3f, 0x60, 0xad, 0x8e, 0x1d, 0xb6, 0x78, 0xc4,
	0xf1, 0xd5, 0x94, 0xcc, 0x4e, 0x64, 0x76, 0xdb, 0x31, 0x2e, 0xd0, 0xa6, 0x1f, 0x70, 0x22, 0x7f,
	0x95, 0xda, 0x58, 0xdd, 0xe3, 0xa2, 0xc9, 0x05, 0xa9, 0x51, 0xc1, 0x54, 0x19, 0xd2, 0x76, 0x6a,
	0x2c, 0xa2, 0x0e, 0x09, 0xa9, 0xe7, 0x6b, 0xaf, 0xd2, 0x2e, 0x7a, 0xdc, 0xe3, 0xf2, 0x91, 0xc4,
	0x4f, 0xfa, 0xf4, 0xba, 0xc7, 0xb9, 0xf7, 0x82, 0x11, 0x1a, 0xfa, 0x84, 0x06, 0x01, 0x8f, 0xa4,
	0x45, 0xe8, 0x7f, 0x8b, 0xa3, 0xa1, 0xfb, 0x64, 0x4a, 0x59, 0x18, 0xad, 0x0c, 0x69, 0x8b, 0x36,
	0x75, 0x45, 0x6b, 0x11, 0xf0, 0xd3, 0x98, 0x73, 0x5b, 0x1e, 0xba, 0x6c, 0xff, 0x80, 0x89, 0xc8,
	0xda, 0x81, 0x8b, 0xa9, 0x53, 0x11, 0xf2, 0x40, 0x30, 0xbc, 0x09, 0xb3, 0xca, 0xbc, 0x84, 0x6e,
	0xa0, 0xe2, 0x7c, 0x79, 0xc5, 0x1e, 0x99, 0x8e, 0xad, 0xac, 0xd5, 0xdc, 0xf1, 0xf7, 0xe5, 0xcc,
	0xc7, 0x5f, 0x9f, 0x57, 0x91, 0xab, 0xbd, 0xd6, 0x2e, 0x5c, 0x92, 0xc5, 0x37, 0xb5, 0x3a, 0xe9,
	0x8a, 0x1f, 0x03, 0x0c, 0x52, 0xd2, 0x2d, 0x0a, 0xb6, 0x8a, 0xd4, 0x8e, 0x23, 0xb5, 0xd5, 0x9b,
	0xd1, 0x91, 0xda, 0xdb, 0xd4, 0x63, 0xda, 0xeb, 0xfe, 0xe1, 0xb4, 0xde, 0x23, 0xb8, 0x7c, 0xba,
	0x83, 0x9e, 0xa0, 0x02, 0xb9, 0x04, 0x32, 0x1e, 0xe2, 0xbf, 0xe2, 0x7c, 0x39, 0x7f, 0xc6, 0x10,
	0x49, 0x01, 0x77, 0xe0, 0xc2, 0x5b, 0x29, 0xca, 0xac, 0xa4, 0xbc, 0x3d, 0x96, 0x52, 0xf5, 0x4f,
	0x61, 0x96, 0xe0, 0x8a, 0xa4, 0xdc, 0x62, 0x51, 0xbf, 0x8f, 0x4e, 0x62, 0x01, 0xb2, 0x7e, 0x5d,
	0x26, 0xf0, 0xbf, 0x9b, 0xf5, 0xeb, 0xd6, 0x0e, 0x2c, 0x0d, 0x4b, 0xf5, 0x48, 0x8f, 0x60, 0x2e,
	0x81, 0xd3, 0x99, 0x4d, 0x34, 0x51, 0xdf, 0x64, 0x55, 0xc0, 0x48, 0xa5, 0x55, 0xed, 0x3c, 0xa1,
	0xa2, 0x91, 0xa0, 0xe4, 0xe1, 0x7c, 0xa2, 0xdc, 0x6d, 0x50, 0xd1, 0x90, 0x3d, 0x72, 0xee, 0xb9,
	0xe4, 0x30, 0xd6, 0x5a, 0xcf, 0xe1, 0xda, 0x5f, 0x4b, 0xfc, 0x23, 0xc4, 0xf2, 0xa7, 0x19, 0x98,
	0x91, 0x0d, 0xf0, 0x1b, 0x04, 0xb3, 0x6a, 0xb5, 0xf0, 0xda, 0x19, 0x35, 0x86, 0x77, 0xda, 0xb0,
	0x27, 0x95, 0x2b, 0x68, 0xab, 0xf4, 0xea, 0xeb, 0xcf, 0xb7, 0xd9, 0x3c, 0x5e, 0x21, 0xe3, 0xae,
	0x12, 0x7e, 0x87, 0x20, 0xd7, 0xdf, 0x35, 0x7c, 0x6f, 0x5c, 0xa3, 0xd3, 0x8b, 0x6f, 0x38, 0x53,
	0x38, 0x34, 0xdd, 0x5d, 0x49, 0x57, 0xc0, 0x37, 0xc9, 0xf8, 0x4f, 0x82, 0xc0, 0x1f, 0x10, 0xcc,
	0x25, 0x35, 0x70, 0x79, 0x5c, 0xb7, 0xe1, 0x85, 0x34, 0xd6, 0xa7, 0xf2, 0x68, 0x46, 0x47, 0x32,
	0xde, 0xc1, 0xa5, 0x49, 0x18, 0xc9, 0xa1, 0x5f, 0x3f, 0xc2, 0x5f, 0x10, 0x2c, 0xa4, 0x97, 0x08,
	0xdf, 0x9f, 0x34, 0x9c, 0xd4, 0xde, 0x1a, 0x0f, 0xa6, 0xb5, 0x69, 0xe8, 0x8a, 0x84, 0x7e, 0x88,
	0x37, 0x26, 0x82, 0x8e, 0x6f, 0x04, 0x39, 0x4c, 0x5d, 0x90, 0xa3, 0xea, 0xc6, 0x71, 0xd7, 0x44,
	0x27, 0x5d, 0x13, 0xfd, 0xe8, 0x9a, 0xe8, 0x75, 0xcf, 0xcc, 0x9c, 0xf4, 0xcc, 0xcc, 0xb7, 0x9e,
	0x99, 0x79, 0xb6, 0x9c, 0xd4, 0x5c, 0x53, 0x45, 0x5f, 0x0e, 0xca, 0x46, 0x9d, 0x90, 0x89, 0xda,
	0xac, 0xfc, 0x2a, 0xaf, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xaa, 0xe8, 0xab, 0x9e, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Get Donation list with pagination
	Donations(ctx context.Context, in *QueryDonationsRequest, opts ...grpc.CallOption) (*QueryDonationsResponse, error)
	// Get Donation By ID
	Donation(ctx context.Context, in *QueryGetDonationRequest, opts ...grpc.CallOption) (*QueryGetDonationResponse, error)
	// Get Donation By Hash
	DonationByHash(ctx context.Context, in *QueryDonationByHashRequest, opts ...grpc.CallOption) (*QueryDonationByHashResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/overgivechain.donation.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Donations(ctx context.Context, in *QueryDonationsRequest, opts ...grpc.CallOption) (*QueryDonationsResponse, error) {
	out := new(QueryDonationsResponse)
	err := c.cc.Invoke(ctx, "/overgivechain.donation.v1.Query/Donations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Donation(ctx context.Context, in *QueryGetDonationRequest, opts ...grpc.CallOption) (*QueryGetDonationResponse, error) {
	out := new(QueryGetDonationResponse)
	err := c.cc.Invoke(ctx, "/overgivechain.donation.v1.Query/Donation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DonationByHash(ctx context.Context, in *QueryDonationByHashRequest, opts ...grpc.CallOption) (*QueryDonationByHashResponse, error) {
	out := new(QueryDonationByHashResponse)
	err := c.cc.Invoke(ctx, "/overgivechain.donation.v1.Query/DonationByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Get Donation list with pagination
	Donations(context.Context, *QueryDonationsRequest) (*QueryDonationsResponse, error)
	// Get Donation By ID
	Donation(context.Context, *QueryGetDonationRequest) (*QueryGetDonationResponse, error)
	// Get Donation By Hash
	DonationByHash(context.Context, *QueryDonationByHashRequest) (*QueryDonationByHashResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Donations(ctx context.Context, req *QueryDonationsRequest) (*QueryDonationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Donations not implemented")
}
func (*UnimplementedQueryServer) Donation(ctx context.Context, req *QueryGetDonationRequest) (*QueryGetDonationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Donation not implemented")
}
func (*UnimplementedQueryServer) DonationByHash(ctx context.Context, req *QueryDonationByHashRequest) (*QueryDonationByHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DonationByHash not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/overgivechain.donation.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Donations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDonationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Donations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/overgivechain.donation.v1.Query/Donations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Donations(ctx, req.(*QueryDonationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Donation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDonationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Donation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/overgivechain.donation.v1.Query/Donation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Donation(ctx, req.(*QueryGetDonationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DonationByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDonationByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DonationByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/overgivechain.donation.v1.Query/DonationByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DonationByHash(ctx, req.(*QueryDonationByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "overgivechain.donation.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Donations",
			Handler:    _Query_Donations_Handler,
		},
		{
			MethodName: "Donation",
			Handler:    _Query_Donation_Handler,
		},
		{
			MethodName: "DonationByHash",
			Handler:    _Query_DonationByHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "overgivechain/donation/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryDonationsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDonationsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDonationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDonationsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDonationsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDonationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Donations) > 0 {
		for iNdEx := len(m.Donations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Donations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDonationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDonationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDonationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDonationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDonationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDonationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Donation != nil {
		{
			size, err := m.Donation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDonationByHashRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDonationByHashRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDonationByHashRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DonationHash) > 0 {
		i -= len(m.DonationHash)
		copy(dAtA[i:], m.DonationHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DonationHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDonationByHashResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDonationByHashResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDonationByHashResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Donation != nil {
		{
			size, err := m.Donation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryDonationsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDonationsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Donations) > 0 {
		for _, e := range m.Donations {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDonationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetDonationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Donation != nil {
		l = m.Donation.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDonationByHashRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DonationHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDonationByHashResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Donation != nil {
		l = m.Donation.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDonationsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDonationsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDonationsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDonationsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDonationsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDonationsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Donations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Donations = append(m.Donations, &Donation{})
			if err := m.Donations[len(m.Donations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDonationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDonationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDonationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDonationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDonationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDonationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Donation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Donation == nil {
				m.Donation = &Donation{}
			}
			if err := m.Donation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDonationByHashRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDonationByHashRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDonationByHashRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DonationHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DonationHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDonationByHashResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDonationByHashResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDonationByHashResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Donation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Donation == nil {
				m.Donation = &Donation{}
			}
			if err := m.Donation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
