// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: overgivechain/donation/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Request for Get Donation By ID
type QueryGetDonationRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetDonationRequest) Reset()         { *m = QueryGetDonationRequest{} }
func (m *QueryGetDonationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDonationRequest) ProtoMessage()    {}
func (*QueryGetDonationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a944054dfe2c36, []int{0}
}
func (m *QueryGetDonationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDonationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDonationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDonationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDonationRequest.Merge(m, src)
}
func (m *QueryGetDonationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDonationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDonationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDonationRequest proto.InternalMessageInfo

func (m *QueryGetDonationRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Response for Get Donation By ID
type QueryGetDonationResponse struct {
	Donation *Donation `protobuf:"bytes,1,opt,name=donation,proto3" json:"donation,omitempty"`
}

func (m *QueryGetDonationResponse) Reset()         { *m = QueryGetDonationResponse{} }
func (m *QueryGetDonationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDonationResponse) ProtoMessage()    {}
func (*QueryGetDonationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a944054dfe2c36, []int{1}
}
func (m *QueryGetDonationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDonationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDonationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDonationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDonationResponse.Merge(m, src)
}
func (m *QueryGetDonationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDonationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDonationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDonationResponse proto.InternalMessageInfo

func (m *QueryGetDonationResponse) GetDonation() *Donation {
	if m != nil {
		return m.Donation
	}
	return nil
}

// Request for Get Donation By Hash
type QueryDonationByHashRequest struct {
	DonationHash string `protobuf:"bytes,1,opt,name=donation_hash,json=donationHash,proto3" json:"donation_hash,omitempty"`
}

func (m *QueryDonationByHashRequest) Reset()         { *m = QueryDonationByHashRequest{} }
func (m *QueryDonationByHashRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDonationByHashRequest) ProtoMessage()    {}
func (*QueryDonationByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a944054dfe2c36, []int{2}
}
func (m *QueryDonationByHashRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDonationByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDonationByHashRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDonationByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDonationByHashRequest.Merge(m, src)
}
func (m *QueryDonationByHashRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDonationByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDonationByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDonationByHashRequest proto.InternalMessageInfo

func (m *QueryDonationByHashRequest) GetDonationHash() string {
	if m != nil {
		return m.DonationHash
	}
	return ""
}

// Response for Get Donation By Hash
type QueryDonationByHashResponse struct {
	Donation *Donation `protobuf:"bytes,1,opt,name=donation,proto3" json:"donation,omitempty"`
}

func (m *QueryDonationByHashResponse) Reset()         { *m = QueryDonationByHashResponse{} }
func (m *QueryDonationByHashResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDonationByHashResponse) ProtoMessage()    {}
func (*QueryDonationByHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a944054dfe2c36, []int{3}
}
func (m *QueryDonationByHashResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDonationByHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDonationByHashResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDonationByHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDonationByHashResponse.Merge(m, src)
}
func (m *QueryDonationByHashResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDonationByHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDonationByHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDonationByHashResponse proto.InternalMessageInfo

func (m *QueryDonationByHashResponse) GetDonation() *Donation {
	if m != nil {
		return m.Donation
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetDonationRequest)(nil), "overgivechain.donation.v1.QueryGetDonationRequest")
	proto.RegisterType((*QueryGetDonationResponse)(nil), "overgivechain.donation.v1.QueryGetDonationResponse")
	proto.RegisterType((*QueryDonationByHashRequest)(nil), "overgivechain.donation.v1.QueryDonationByHashRequest")
	proto.RegisterType((*QueryDonationByHashResponse)(nil), "overgivechain.donation.v1.QueryDonationByHashResponse")
}

func init() {
	proto.RegisterFile("overgivechain/donation/v1/query.proto", fileDescriptor_10a944054dfe2c36)
}

var fileDescriptor_10a944054dfe2c36 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcd, 0x2f, 0x4b, 0x2d,
	0x4a, 0xcf, 0x2c, 0x4b, 0x4d, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x4f, 0xc9, 0xcf, 0x4b, 0x2c, 0xc9,
	0xcc, 0xcf, 0xd3, 0x2f, 0x33, 0xd4, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x92, 0x44, 0x51, 0xa6, 0x07, 0x53, 0xa6, 0x57, 0x66, 0x28, 0x25, 0x98, 0x98, 0x9b,
	0x99, 0x97, 0xaf, 0x0f, 0x26, 0x21, 0xaa, 0xa5, 0xb4, 0x92, 0xf3, 0x8b, 0x73, 0xf3, 0x8b, 0xf5,
	0x93, 0x12, 0x8b, 0x53, 0x21, 0xc6, 0xe8, 0x97, 0x19, 0x26, 0xa5, 0x96, 0x24, 0x1a, 0xea, 0x17,
	0x24, 0xa6, 0x67, 0x42, 0xf5, 0x42, 0xd4, 0x8a, 0xa4, 0xe7, 0xa7, 0xe7, 0x83, 0x99, 0xfa, 0x20,
	0x16, 0x54, 0x54, 0x26, 0x3d, 0x3f, 0x3f, 0x3d, 0x27, 0x55, 0x3f, 0xb1, 0x20, 0x53, 0x3f, 0x31,
	0x2f, 0x2f, 0xbf, 0x04, 0xac, 0xa5, 0x18, 0x2a, 0xab, 0x81, 0xdb, 0xd1, 0x70, 0x97, 0x41, 0x54,
	0xaa, 0xe1, 0x56, 0x59, 0x90, 0x58, 0x94, 0x98, 0x0b, 0x35, 0x51, 0x49, 0x93, 0x4b, 0x3c, 0x10,
	0xe4, 0x4e, 0xf7, 0xd4, 0x12, 0x17, 0xa8, 0x9a, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0xa6, 0xcc, 0x14, 0xa5,
	0x68, 0x2e, 0x09, 0x4c, 0xa5, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xf6, 0x5c, 0x1c, 0x30,
	0x2b, 0xc0, 0x3a, 0xb8, 0x8d, 0x94, 0xf5, 0x70, 0x86, 0x9c, 0x1e, 0x5c, 0x3b, 0x5c, 0x93, 0x92,
	0x23, 0x97, 0x14, 0xd8, 0x70, 0x98, 0x94, 0x53, 0xa5, 0x47, 0x62, 0x71, 0x06, 0xcc, 0x29, 0xca,
	0x5c, 0xbc, 0x30, 0x95, 0xf1, 0x19, 0x89, 0xc5, 0x19, 0x60, 0x3b, 0x38, 0x83, 0x78, 0x60, 0x82,
	0x20, 0xb5, 0x4a, 0x71, 0x5c, 0xd2, 0x58, 0x8d, 0xa0, 0x92, 0x13, 0x8d, 0x2e, 0x32, 0x71, 0xb1,
	0x82, 0x2d, 0x10, 0x9a, 0xc2, 0xc8, 0xc5, 0x01, 0x53, 0x20, 0x64, 0x84, 0xc7, 0x14, 0x1c, 0x41,
	0x2b, 0x65, 0x4c, 0x92, 0x1e, 0x88, 0x07, 0x94, 0xe4, 0x9b, 0x2e, 0x3f, 0x99, 0xcc, 0x24, 0x29,
	0x24, 0xae, 0x0f, 0xd3, 0x8c, 0x88, 0xd6, 0xea, 0xcc, 0x94, 0x5a, 0xa1, 0x0d, 0x8c, 0x5c, 0x7c,
	0xa8, 0x9e, 0x17, 0x32, 0x25, 0x64, 0x11, 0xd6, 0xf0, 0x96, 0x32, 0x23, 0x55, 0x1b, 0xd4, 0x89,
	0xfa, 0x60, 0x27, 0x6a, 0x0a, 0xa9, 0x63, 0x71, 0x22, 0x28, 0xde, 0xf4, 0xab, 0x51, 0xa2, 0xb1,
	0xd6, 0xc9, 0xf2, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c,
	0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0xe4, 0x61, 0x26,
	0xe8, 0x42, 0x52, 0x70, 0x05, 0xc2, 0xa4, 0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24, 0x36, 0x70, 0x02,
	0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xfd, 0xb6, 0xd1, 0xc9, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Get Donation By ID
	Donation(ctx context.Context, in *QueryGetDonationRequest, opts ...grpc.CallOption) (*QueryGetDonationResponse, error)
	// Get Donation By ID
	DonationByHash(ctx context.Context, in *QueryDonationByHashRequest, opts ...grpc.CallOption) (*QueryDonationByHashResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Donation(ctx context.Context, in *QueryGetDonationRequest, opts ...grpc.CallOption) (*QueryGetDonationResponse, error) {
	out := new(QueryGetDonationResponse)
	err := c.cc.Invoke(ctx, "/overgivechain.donation.v1.Query/Donation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DonationByHash(ctx context.Context, in *QueryDonationByHashRequest, opts ...grpc.CallOption) (*QueryDonationByHashResponse, error) {
	out := new(QueryDonationByHashResponse)
	err := c.cc.Invoke(ctx, "/overgivechain.donation.v1.Query/DonationByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Get Donation By ID
	Donation(context.Context, *QueryGetDonationRequest) (*QueryGetDonationResponse, error)
	// Get Donation By ID
	DonationByHash(context.Context, *QueryDonationByHashRequest) (*QueryDonationByHashResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Donation(ctx context.Context, req *QueryGetDonationRequest) (*QueryGetDonationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Donation not implemented")
}
func (*UnimplementedQueryServer) DonationByHash(ctx context.Context, req *QueryDonationByHashRequest) (*QueryDonationByHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DonationByHash not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Donation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDonationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Donation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/overgivechain.donation.v1.Query/Donation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Donation(ctx, req.(*QueryGetDonationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DonationByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDonationByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DonationByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/overgivechain.donation.v1.Query/DonationByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DonationByHash(ctx, req.(*QueryDonationByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "overgivechain.donation.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Donation",
			Handler:    _Query_Donation_Handler,
		},
		{
			MethodName: "DonationByHash",
			Handler:    _Query_DonationByHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "overgivechain/donation/v1/query.proto",
}

func (m *QueryGetDonationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDonationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDonationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDonationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDonationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDonationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Donation != nil {
		{
			size, err := m.Donation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDonationByHashRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDonationByHashRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDonationByHashRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DonationHash) > 0 {
		i -= len(m.DonationHash)
		copy(dAtA[i:], m.DonationHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DonationHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDonationByHashResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDonationByHashResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDonationByHashResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Donation != nil {
		{
			size, err := m.Donation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetDonationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetDonationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Donation != nil {
		l = m.Donation.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDonationByHashRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DonationHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDonationByHashResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Donation != nil {
		l = m.Donation.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetDonationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDonationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDonationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDonationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDonationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDonationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Donation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Donation == nil {
				m.Donation = &Donation{}
			}
			if err := m.Donation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDonationByHashRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDonationByHashRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDonationByHashRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DonationHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DonationHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDonationByHashResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDonationByHashResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDonationByHashResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Donation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Donation == nil {
				m.Donation = &Donation{}
			}
			if err := m.Donation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
