// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: overgivechain/delivery/v1/delivery.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Delivery struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignId   string `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Title        string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	NoteHash     string `protobuf:"bytes,4,opt,name=note_hash,json=noteHash,proto3" json:"note_hash,omitempty"`
	DeliveryHash string `protobuf:"bytes,5,opt,name=delivery_hash,json=deliveryHash,proto3" json:"delivery_hash,omitempty"`
	Creator      string `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	RecordedAt   int64  `protobuf:"varint,7,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
}

func (m *Delivery) Reset()         { *m = Delivery{} }
func (m *Delivery) String() string { return proto.CompactTextString(m) }
func (*Delivery) ProtoMessage()    {}
func (*Delivery) Descriptor() ([]byte, []int) {
	return fileDescriptor_561ba071f1c5b60a, []int{0}
}
func (m *Delivery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Delivery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Delivery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Delivery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delivery.Merge(m, src)
}
func (m *Delivery) XXX_Size() int {
	return m.Size()
}
func (m *Delivery) XXX_DiscardUnknown() {
	xxx_messageInfo_Delivery.DiscardUnknown(m)
}

var xxx_messageInfo_Delivery proto.InternalMessageInfo

func (m *Delivery) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Delivery) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *Delivery) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Delivery) GetNoteHash() string {
	if m != nil {
		return m.NoteHash
	}
	return ""
}

func (m *Delivery) GetDeliveryHash() string {
	if m != nil {
		return m.DeliveryHash
	}
	return ""
}

func (m *Delivery) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Delivery) GetRecordedAt() int64 {
	if m != nil {
		return m.RecordedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Delivery)(nil), "overgivechain.delivery.v1.Delivery")
}

func init() {
	proto.RegisterFile("overgivechain/delivery/v1/delivery.proto", fileDescriptor_561ba071f1c5b60a)
}

var fileDescriptor_561ba071f1c5b60a = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xe3, 0xf4, 0xff, 0xf2, 0x33, 0x58, 0x0c, 0x46, 0x48, 0x6e, 0x04, 0x4b, 0x16, 0x5a,
	0x55, 0x4c, 0x8c, 0x20, 0x06, 0x58, 0x33, 0xb2, 0x44, 0x26, 0xbe, 0x6a, 0x2c, 0x95, 0x38, 0x72,
	0x2c, 0x8b, 0xbe, 0x05, 0x8f, 0xc5, 0x84, 0x3a, 0x32, 0xa2, 0xe4, 0x45, 0x50, 0x1d, 0x5c, 0xc4,
	0xe6, 0x73, 0xce, 0x27, 0xf9, 0xea, 0x83, 0x54, 0x3b, 0x34, 0x6b, 0xe5, 0xb0, 0x28, 0x85, 0xaa,
	0x96, 0x12, 0x37, 0xca, 0xa1, 0xd9, 0x2e, 0xdd, 0xea, 0xf0, 0x5e, 0xd4, 0x46, 0x5b, 0x4d, 0xcf,
	0xff, 0x91, 0x8b, 0xc3, 0xea, 0x56, 0x97, 0x9f, 0x04, 0xa6, 0x0f, 0xbf, 0x99, 0x9e, 0x42, 0xac,
	0x24, 0x23, 0x09, 0x49, 0x87, 0x59, 0xac, 0x24, 0x9d, 0xc3, 0x51, 0x21, 0x5e, 0x6b, 0xa1, 0xd6,
	0x55, 0xae, 0x24, 0x8b, 0x13, 0x92, 0xce, 0x32, 0x08, 0xd5, 0x93, 0xa4, 0x67, 0x30, 0xb2, 0xca,
	0x6e, 0x90, 0x0d, 0xfc, 0xd4, 0x07, 0x7a, 0x01, 0xb3, 0x4a, 0x5b, 0xcc, 0x4b, 0xd1, 0x94, 0x6c,
	0xe8, 0x97, 0xe9, 0xbe, 0x78, 0x14, 0x4d, 0x49, 0xaf, 0xe0, 0x24, 0xfc, 0xdf, 0x03, 0x23, 0x0f,
	0x1c, 0x87, 0xd2, 0x43, 0x0c, 0x26, 0x85, 0x41, 0x61, 0xb5, 0x61, 0x63, 0x3f, 0x87, 0xb8, 0x3f,
	0xc9, 0x60, 0xa1, 0x8d, 0x44, 0x99, 0x0b, 0xcb, 0x26, 0x09, 0x49, 0x07, 0x19, 0x84, 0xea, 0xce,
	0xde, 0xdf, 0x7e, 0xb4, 0x9c, 0xec, 0x5a, 0x4e, 0xbe, 0x5b, 0x4e, 0xde, 0x3b, 0x1e, 0xed, 0x3a,
	0x1e, 0x7d, 0x75, 0x3c, 0x7a, 0x9e, 0x07, 0x0b, 0xd7, 0xbd, 0xb0, 0xb7, 0x3f, 0x65, 0x76, 0x5b,
	0x63, 0xf3, 0x32, 0xf6, 0xb6, 0x6e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x5f, 0xef, 0x5f,
	0x59, 0x01, 0x00, 0x00,
}

func (m *Delivery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Delivery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Delivery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RecordedAt != 0 {
		i = encodeVarintDelivery(dAtA, i, uint64(m.RecordedAt))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintDelivery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DeliveryHash) > 0 {
		i -= len(m.DeliveryHash)
		copy(dAtA[i:], m.DeliveryHash)
		i = encodeVarintDelivery(dAtA, i, uint64(len(m.DeliveryHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.NoteHash) > 0 {
		i -= len(m.NoteHash)
		copy(dAtA[i:], m.NoteHash)
		i = encodeVarintDelivery(dAtA, i, uint64(len(m.NoteHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintDelivery(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CampaignId) > 0 {
		i -= len(m.CampaignId)
		copy(dAtA[i:], m.CampaignId)
		i = encodeVarintDelivery(dAtA, i, uint64(len(m.CampaignId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintDelivery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDelivery(dAtA []byte, offset int, v uint64) int {
	offset -= sovDelivery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Delivery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovDelivery(uint64(m.Id))
	}
	l = len(m.CampaignId)
	if l > 0 {
		n += 1 + l + sovDelivery(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovDelivery(uint64(l))
	}
	l = len(m.NoteHash)
	if l > 0 {
		n += 1 + l + sovDelivery(uint64(l))
	}
	l = len(m.DeliveryHash)
	if l > 0 {
		n += 1 + l + sovDelivery(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovDelivery(uint64(l))
	}
	if m.RecordedAt != 0 {
		n += 1 + sovDelivery(uint64(m.RecordedAt))
	}
	return n
}

func sovDelivery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDelivery(x uint64) (n int) {
	return sovDelivery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Delivery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDelivery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Delivery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Delivery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelivery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelivery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelivery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelivery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CampaignId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelivery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelivery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelivery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoteHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelivery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelivery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelivery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NoteHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeliveryHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelivery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelivery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelivery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeliveryHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelivery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelivery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelivery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordedAt", wireType)
			}
			m.RecordedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelivery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDelivery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDelivery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDelivery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDelivery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDelivery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDelivery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDelivery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDelivery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDelivery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDelivery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDelivery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDelivery = fmt.Errorf("proto: unexpected end of group")
)
